version: "3.7"

volumes:
  nhm:
    driver: local

services:

  gridmets2s:
      build:
        context: ./nhmusgs-gridmetetl-s2s
        args:
          insecure: "-k"
        labels:
          - "gov.usgs.nhm.image.docker.application=NHM"
          - "gov.usgs.nhm.image.docker.type=GRIDMETETL_S2S"
      image: nhmusgs/gridmetetl-s2s
      container_name: gridmetetl-s2s
      environment:
        - CBH_IDIR
        - START_DATE
        - END_DATE
        - NHM_SOURCE_DIR
      env_file:
        - nhm.env
      volumes:
        - nhm:/nhm